# Generated by Django 2.2.10 on 2020-08-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
                ('gender', models.CharField(default='', max_length=256)),
                ('company', models.CharField(default='', max_length=256)),
                ('city', models.CharField(default='', max_length=256)),
                ('title', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
